default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost

development:
  <<: *default
  database: exposition_development
  port: 5433
test:
  <<: *default
  database: exposition_test
  port: 5433

